server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: image-service

firebase:
  bucket:
    name: ecommerce-549f0.appspot.com
  get:
    image:
      url: https://firebasestorage.googleapis.com/v0/b/${firebase.bucket.name}/o/%s?alt=media